export type { OCROptions } from "@/services/ocr";

// ─── Types ───
export type {
  AIResponse,
  AIResponseStream,
  AIRequestOptions,
  AITextOptions,
  AIMessage,
  AISystemMessage,
  AIUsage,
  AIError,
  AIErrorCode,
  AISession,
  AIProviderType,
  AIProviderConfig,
  AIServiceStatus,
  AIProcessingMetrics,
  AIHealthStatus,
  AIQuotaInfo,
  AIStreamChunk,
  AIStreamToken,
  AIStreamToolCall,
  AIStreamToolResult,
  AIStreamEnd,
  AIStreamError,
  AIStreamEvent,
} from "./types/common";

export type {
  AITradeAnalysis,
  AITradeReview,
  AIPerformanceMetrics,
  AITradeInsights,
  AIJournalAnalysis,
  AIWinRateAnalysis,
  AIEmotionAnalysis,
  AITradePattern,
  AIRecommendation,
  AIConfidence,
  AIFeedback,
  AITradeSummary,
  AITradeQuery,
  AIAnalysisResult,
  AIAnalysisStatus,
  AIProcessingStage,
  AIMarketContext,
  AIPositionAnalysis,
  AIPositionSize,
  AICorrelation,
  AITradeSimilarity,
  AIPeriod,
  AIComparison,
  AIComparisonType,
  AIPerformanceBreakdown,
  AITradeStrength,
  AITradeWeakness,
  AITradeOpportunity,
  AITradeThreat,
  AISWOTAnalysis,
  AIImprovementArea,
  AIGoalProgress,
  AITradingGoal,
  AITradingPlan,
  AITradingPlanStep,
  AITradingPlanStatus,
  AITradingPlanReview,
} from "./types/trade-analysis";

export type {
  AIChartAnalysis,
  AIChartPattern,
  AIChartIndicator,
  AIChartSignal,
  AIChartTrend,
  AIChartSupportResistance,
  AIChartFibonacci,
  AIChartWave,
  AIChartCandlestick,
  AIChartTimeframe,
  AIChartType,
  AIChartFeature,
  AIChartFeatureType,
  AIChartFeatureConfidence,
  AIChartFeatureLocation,
  AIChartFeatureMetadata,
  AIChartAnalysisResult,
  AIChartAnalysisStatus,
  AIChartAnalysisOptions,
  AIChartAnalysisRequest,
  AIChartAnalysisResponse,
  AIChartProviderType,
  AIChartProvider,
  AIChartProviderConfig,
  AIChartProviderStatus,
  AIChartProviderCapabilities,
  AIChartProviderLimitations,
  AIChartProviderQuota,
  AIChartProviderUsage,
  AIChartProviderHealth,
} from "./types/chart-analysis";

export type {
  OCRRequest,
  OCRResponse,
  OCRProvider,
  OCRProviderType,
  OCRProviderConfig,
  OCRProviderStatus,
  OCRProviderCapabilities,
  OCRProviderLimitations,
  OCRProviderQuota,
  OCRProviderUsage,
  OCRProviderHealth,
  OCRImage,
  OCRText,
  OCRWord,
  OCRLine,
  OCRParagraph,
  OCRBlock,
  OCRRegion,
  OCRLanguage,
  OCRConfidence,
  OCRError,
  OCRErrorCode,
  OCRProcessingOptions,
  OCRProcessingResult,
  OCRProcessingStatus,
  OCRProcessingStage,
  OCRQualityMetrics,
  OCRQualityScore,
  OCRQualityLevel,
  OCRQualityAssessment,
  OCRQualityReport,
  OCRQualityIssue,
  OCRQualityIssueType,
  OCRQualityIssueSeverity,
  OCRQualityIssueLocation,
  OCRQualityIssueRecommendation,
  OCRPreprocessingOptions,
  OCRPreprocessingResult,
  OCRPreprocessingStatus,
  OCRPreprocessingStage,
  OCRPostprocessingOptions,
  OCRPostprocessingResult,
  OCRPostprocessingStatus,
  OCRPostprocessingStage,
  OCRTextExtraction,
  OCRTextExtractionOptions,
  OCRTextExtractionResult,
  OCRTextExtractionStatus,
  OCRTextExtractionStage,
  OCRTextRecognition,
  OCRTextRecognitionOptions,
  OCRTextRecognitionResult,
  OCRTextRecognitionStatus,
  OCRTextRecognitionStage,
  OCRTextDetection,
  OCRTextDetectionOptions,
  OCRTextDetectionResult,
  OCRTextDetectionStatus,
  OCRTextDetectionStage,
  OCRTextStructure,
  OCRTextStructureOptions,
  OCRTextStructureResult,
  OCRTextStructureStatus,
  OCRTextStructureStage,
  OCRTextAnalysis,
  OCRTextAnalysisOptions,
  OCRTextAnalysisResult,
  OCRTextAnalysisStatus,
  OCRTextAnalysisStage,
  OCRTextUnderstanding,
  OCRTextUnderstandingOptions,
  OCRTextUnderstandingResult,
  OCRTextUnderstandingStatus,
  OCRTextUnderstandingStage,
  OCRTextReasoning,
  OCRTextReasoningOptions,
  OCRTextReasoningResult,
  OCRTextReasoningStatus,
  OCRTextReasoningStage,
} from "./types/ocr";

export type {
  AICoachingSession,
  AICoachingMessage,
  AICoachingResponse,
  AICoachingContext,
  AICoachingGoal,
  AICoachingPlan,
  AICoachingProgress,
  AICoachingFeedback,
  AICoachingInsight,
  AICoachingRecommendation,
  AICoachingStrategy,
  AICoachingTechnique,
  AICoachingExercise,
  AICoachingAssessment,
  AICoachingMetrics,
  AICoachingPersonality,
  AICoachingStyle,
  AICoachingMode,
  AICoachingLevel,
  AICoachingTopic,
  AICoachingQuestion,
  AICoachingAnswer,
  AICoachingScenario,
  AICoachingRole,
  AICoachingPersona,
  AICoachingTone,
  AICoachingVoice,
  AICoachingLanguage,
  AICoachingConfig,
  AICoachingOptions,
  AICoachingRequest,
  AICoachingResult,
  AICoachingStatus,
  AICoachingProvider,
  AICoachingProviderType,
  AICoachingProviderConfig,
  AICoachingProviderStatus,
  AICoachingProviderCapabilities,
  AICoachingProviderLimitations,
  AICoachingProviderQuota,
  AICoachingProviderUsage,
  AICoachingProviderHealth,
} from "./types/coaching";

export type {
  AITranscriptionRequest,
  AITranscriptionResponse,
  AITranscriptionSegment,
  AITranscriptionWord,
  AITranscriptionSpeaker,
  AITranscriptionLanguage,
  AITranscriptionConfidence,
  AITranscriptionError,
  AITranscriptionErrorCode,
  AITranscriptionProvider,
  AITranscriptionProviderType,
  AITranscriptionProviderConfig,
  AITranscriptionProviderStatus,
  AITranscriptionProviderCapabilities,
  AITranscriptionProviderLimitations,
  AITranscriptionProviderQuota,
  AITranscriptionProviderUsage,
  AITranscriptionProviderHealth,
  AITranscriptionOptions,
  AITranscriptionResult,
  AITranscriptionStatus,
  AITranscriptionStage,
  AITranscriptionQuality,
  AITranscriptionQualityMetrics,
  AITranscriptionQualityScore,
  AITranscriptionQualityLevel,
  AITranscriptionQualityAssessment,
  AITranscriptionQualityReport,
  AITranscriptionQualityIssue,
  AITranscriptionQualityIssueType,
  AITranscriptionQualityIssueSeverity,
  AITranscriptionQualityIssueLocation,
  AITranscriptionQualityIssueRecommendation,
  AITranscriptionProcessingOptions,
  AITranscriptionProcessingResult,
  AITranscriptionProcessingStatus,
  AITranscriptionProcessingStage,
  AITranscriptionPreprocessingOptions,
  AITranscriptionPreprocessingResult,
  AITranscriptionPreprocessingStatus,
  AITranscriptionPreprocessingStage,
  AITranscriptionPostprocessingOptions,
  AITranscriptionPostprocessingResult,
  AITranscriptionPostprocessingStatus,
  AITranscriptionPostprocessingStage,
} from "./types/transcription";

// ─── Screenshot Analysis (Phase 7C) ───
export type {
  ScreenshotAnalysis,
  AnalysisHistory,
  AnalysisStatus,
  ImageQualityMetrics,
  FieldConfidenceDetail,
  ExtractedTradeData,
  TradeAdvice,
  JournalInsight,
  WorkspaceDashboardStats,
  GroupedAnalyses,
  HistoryGroup,
  HistoryFilters,
  HistorySort,
} from "./types/screenshot-analysis";

export {
  getHistory,
  saveAnalysis,
  updateAnalysis,
  getAnalysis,
  deleteAnalysis,
  duplicateAnalysis,
  getAllAnalyses,
  filterAnalyses,
  groupAnalysesByDate,
  getDashboardStats,
  markAsImported,
  clearHistory,
  getStorageInfo,
} from "./historyStorage";

export { analyzeImageQuality } from "./imageQuality";

export { generateTradeAdvice, ocrResultToExtractedTrade } from "./aiTradeAdvice";

// ─── Utils ───
export {
  delay,
  simulateProcessing,
  generateAIId,
  withRetry,
  isAbortError,
  getErrorMessage,
  formatProcessingTime,
  clamp,
  randomPick,
  randomInt,
  randomFloat,
} from "./utils";

// ─── Provider Factory & Registry ───
export { ProviderFactory, providerFactory, ProviderFactoryError } from "./providers/factory";
export { ProviderRegistry, providerRegistry } from "./providers/registry";
